dependencies {
    implementation(project(":MEME-DOMAIN"))
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    runtimeOnly 'com.mysql:mysql-connector-j'
    // Mockito
    testImplementation 'org.mockito:mockito-core:5.8.0'
    runtimeOnly 'com.h2database:h2'  // h2 추가

    // Logstash에서 처리할 수 있는 JSON 형식으로 로그 메시지를 인코딩
    implementation 'net.logstash.logback:logstash-logback-encoder:6.2'

    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    // Reddison
    implementation 'org.redisson:redisson-spring-boot-starter:3.18.0'
}

test {
    useJUnitPlatform()
}

jar {
    enabled = false
}

tasks.register("prepareKotlinBuildScriptModel") {

}