version: '3'
services:
  auth:
    container_name: auth
    image: sunwupark/meme-server-auth
    expose:
      - 8080
    ports:
      - "8080:8080"

  reservation:
    container_name: reservation
    image: sunwupark/meme-server-reservation
    expose:
      - 8081
    ports:
      - "8081:8081"

  notification:
    container_name: notification
    image: sunwupark/meme-server-notification
    expose:
      - 8082
    ports:
      - "8082:8082"

  service:
    container_name: service
    image: sunwupark/meme-server-service
    expose:
      - 8083
    ports:
      - "8083:8083"