spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;MODE=MYSQL;NON_KEYWORDS=USER
    username: sa
    password:

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  security:
    oauth2:
      kakao:
        issuer: "https://kauth.kakao.com"
        rest-api-key: ${KAKAO_REST_API_KEY}
      apple:
        issuer: "https://appleid.apple.com"
        client-id: ${APPLE_CLIENT_ID}

jwt:
  issuer: meme_umc
  secret-key: ${JWT_SECRET_KEY}
  access-token-validity-in-seconds: 1800  # 30 minutes
  refresh-token-validity-in-seconds: 86400  # 24 hours

springdoc:
  swagger-ui:
    path: /auth/swagger-ui
    display-request-duration: true
  api-docs:
    path: /auth/docs