server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

security:
  user:
    name: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
    roles: ${ADMIN_ROLES}